# Generated by Django 4.2.3 on 2023-07-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_rename_todotask_customtodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtodo',
            old_name='status',
            new_name='is_completed',
        ),
    ]
